### PR TITLE
Optimistic domain host

### PR DESCRIPTION
**Pull request by maciejka**

### CODE REVIEW

**Comment by hexonaut** [comment]
Can you provide an example of Starknet and why it doesn't fit with the current paradigm? Don't worry about making it run as I can work on the actual PR.

**Comment by maciejka** [comment]
> Can you provide an example of Starknet and why it doesn't fit with the current paradigm? Don't worry about making it run as I can work on the actual PR.

See: https://github.com/maciejka/dss-bridge/pull/1
Main problem is different way of receiving l2->l1 messages.

**Comment by gbalabasquer** [comment]
I think we can remove `OptimisticDomainHost.sol` and just do this part directly in each specific implementation, like we did with the payload avoiding an intermediate contract.

**Comment by hexonaut** [comment]
Ok, I see what you're saying. The auth should be handled in the implementation. Will make these changes.

**Comment by hexonaut** [comment]
Done: https://github.com/makerdao/dss-bridge/pull/6

**Pull request closed without merging**
